version: "3.3"
services:
  cocktail-compass-db:
    image: postgres:latest
    restart: always
    #    volumes:
    #      - ./.postgres-data:/var/lib/postgresql/data
    #    env_file: ./.env-postgres
    environment:
      POSTGRES_USER: admin_robbie
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cocktail-compass
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "1234:8080"
