## DB config goes here
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      platform: postgresql
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/sqlbootcamp
    username: pguserx
    password: pgpassword
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
## Logging settings
debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

example:
  app:
      jwtSecret: generateSecretHere
      jwtExpirationMs: 86400000